require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ting' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'FirebaseAnalytics'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'


  target 'tingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ting-tvOS' do
  # Pods for ting-tvOS

  target 'ting-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
